---

# config_developer

# mongo_path: /hddlinux/mongodb
mongo_path: /var/lib/mongodb
php_log_folder: /var/log/php
lf_path: /var/www/default_local/web-languageforge
sf_path: /var/www/default_local/web-languageforge
site_src_paths:
  - "{{lf_path}}/src"
  - "{{sf_path}}/src"

### Version/distro
base_distribution: "{{ansible_distribution | lower}}"
base_distribution_release: "{{ansible_distribution_release}}"

node_version: 10.16.0
npm_version: 6.10.0
mongodb_version: 4.0
php_version: 7.3

### SSL config
ssl_letsencrypt_install: false

ssl_items:
  - name: scriptureforge
    state: selfsign
    request:
        country_code: "TH"
        state: "Chiang Mai"
        locality: "Chiang Mai"
        organization: "SIL"
        organization_unit: ""
        common_name: "scriptureforge.local"
        alt_names:
          - key: DNS.1
            value: "www.scriptureforge.local"
          - key: DNS.2
            value: "scriptureforge.local"
    sign:


### Apache config
apache_module_enable:
  - headers
  - proxy
  - proxy_http
  - proxy_wstunnel
  - rewrite
  - ssl

apache_site_enable:
  - default_local.conf
  - languageforge_org.conf
  - scriptureforge_org.conf

apache_vhosts:
  - server_name: default.local
    server_admin: webmaster@palaso.org
    server_file_name: default_local
    template: vhost_proxypath_ssl.conf.j2
    document_root: /var/www/default_local
    directory_options:
      - "+Indexes"
      - "+FollowSymLinks"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - localhost
  - server_name: languageforge.org
    server_admin: webmaster@palaso.org
    server_file_name: languageforge_org
    template: vhost_proxypath_ssl.conf.j2
    document_root: /var/www/languageforge.org/htdocs
    link_to: "{{lf_path}}/src"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - languageforge.localhost
          - localhost
        extra:
          - '<ifModule mod_headers.c>'
          - '    <Files "service-worker.js">'
          - '        Header Set Service-Worker-allowed "/"'
          - '    </Files>'
          - '</IfModule>'
  - server_name: scriptureforge.org
    server_admin: webmaster@palaso.org
    server_file_name: scriptureforge_org
    template: vhost_proxypath_ssl.conf.j2
    document_root: /var/www/scriptureforge.org/htdocs
    link_to: "{{sf_path}}/src"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - scriptureforge.localhost
          - localhost
        extra:
        - '<ifModule mod_headers.c>'
        - '    <Files "service-worker.js">'
        - '        Header Set Service-Worker-allowed "/"'
        - '    </Files>'
        - '</IfModule>'
      - has_ssl: true
        port: 443
        certificate_file: "scriptureforge.pem"
        key_file: "scriptureforge.key"
        extra:
        - '<ifModule mod_headers.c>'
        - '    <Files "service-worker.js">'
        - '        Header Set Service-Worker-allowed "/"'
        - '    </Files>'
        - '</IfModule>'
